# Generated by Django 6.0.7 on 2026-08-02 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('color_key', models.CharField(choices=[('random', 'Random'), ('school', 'School'), ('personal', 'Personal'), ('drama', 'Drama')], max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='notes.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', 'id'),
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='note_owner_updated_idx'), models.Index(fields=['owner', 'category', '-updated_at'], name='note_owner_cat_updated_idx')],
            },
        ),
    ]
