# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


def seed_manual_order(apps, schema_editor):
    Note = apps.get_model("notes", "Note")
    owner_ids = Note.objects.order_by().values_list("owner_id", flat=True).distinct()
    for owner_id in owner_ids.iterator():
        notes = list(
            Note.objects.filter(owner_id=owner_id).order_by("created_at", "id")
        )
        for position, note in enumerate(notes):
            note.manual_order = position
        Note.objects.bulk_update(notes, ("manual_order",))


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_note_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="manual_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_manual_order, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["owner", "manual_order", "id"],
                name="note_owner_manual_idx",
            ),
        ),
    ]
